### ISSUE TITLE
WaveFile Inject index out of range

### ISSUE THREAD

**Issue by PhyTensor** [ocluse/LiquidSnow-archive#11]
![aretha_issue](https://user-images.githubusercontent.com/35362037/107864262-8103d480-6e6b-11eb-866d-3d2418e6b81c.png)

We need an urgent fix for this.

**Comment by PhyTensor** [comment]
I believe with your expertise, this should be quite a simple fix, within minutes

**Comment by thismaker** [comment]
Thanks for bringing attention to that. Fixed. Error was caused by using the wrong file sizes.
