### ISSUE TITLE
Flexible input prompt

### ISSUE THREAD

**Issue by PhyTensor** [ocluse/LiquidSnow-archive#17]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using the prompt as it is very repetitive, makes me very tired when typing.

**Describe the solution you'd like**
A flexible input prompt much like that used in projects such as Metasploit Framework,

**If it is not related to any problem**
I am so used to the terminal and need to use it efficiently and effectively, hence less typing more work philosophy.

**Additional context**
You're doing pretty good on the color scheme, very nice.

**Comment by thismaker** [comment]
this issue is currently being worked on.
