### ISSUE TITLE
Phytensor.QuantumCrypt

### ISSUE THREAD

**Issue by thismaker** [ocluse/LiquidSnow-archive#23]
@Phystro I'm about to PR feature to main pending the release of v1.1.0.0 where are you with the development of `Phytensor.QuantumCrypt` and should I forego it instead for this release?` Thismaker.Thoth` is not yet in @main but it is very complete.

**Comment by PhyTensor** [comment]
Forego it for now ju sijaongeza any worthwhile code hapo kwa a long time, nikipata an ease in tasks i should have something by then

**Comment by thismaker** [comment]
Alright then, but also you still have some time, since I've postponed the release coz I'm adding a new type of `Aba.Client` that uses `Thismaker.Mercury`, I noticed that the other Hub based one is not suitable for all scenarios, for example in Alox and Cosmos, so the newer client should be suitable to work in that environment.
